# Generated by Django 3.2.4 on 2021-06-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('Feriados Nacionais e Estaduais', 'Feriados Nacionais e Estaduais'), ('Feriados Municipais', 'Feriados Municipais'), ('Datas Comemorativas', 'Datas Comemorativas'), ('Datas da Instituinção', 'Datas da Instituinção')], max_length=250),
        ),
    ]
